[package]
name = "mithril-end-to-end"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
clap = { version = "3.1.6", features = ["derive"] }
glob = "0.3"
hex = "0.4.3"
mithril-common = { path = "../../mithril-common", features = ["test-utils"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.10"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-async = "2.7.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"
thiserror = "1.0.31"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.1", features = ["codec"] }

[features]
portable = ["mithril-common/portable"]
