version: "3.9"

services:
  cardano-node-signer:
    image: cardano-node/1.35.3-modified
    container_name: cardano-node-signer-${SIGNER_ID}
    build:
      context: .
      dockerfile: Dockerfile.cardano
    user: ${CURRENT_UID}
    profiles:
      - cardano
      - all
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./cardano-configurations/network/${NETWORK}:/config
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/db:/db
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    command:
      [
        "run",
        "--config",
        "/config/cardano-node/config.json",
        "--topology",
        "/config/cardano-node/topology.json",
        "--database-path",
        "/db"
      ]

  mithril-signer:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID}
    container_name: mithril-signer-${SIGNER_ID}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=${NETWORK}
      - PARTY_ID=${PARTY_ID}
      - RUN_INTERVAL=240000
      - DB_DIRECTORY=/db
      - DATA_STORES_DIRECTORY=/mithril-signer-${SIGNER_ID}/mithril/stores
      - STORE_RETENTION_LIMIT=5
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/mithril:/mithril-signer-${SIGNER_ID}/mithril
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/db:/db
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  default:
    external:
      name: mithril_network
