version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - tools
      - all
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail:1.4.1
    profiles:
      - tools
      - all
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml

networks:
  default:
    external:
      name: mithril_network
