version: "3.9"

services:
  cardano-node-aggregator:
    image: cardano-node/1.35.3-modified
    container_name: cardano-node-aggregator
    build:
      context: .
      dockerfile: Dockerfile.cardano
    user: ${CURRENT_UID}
    profiles:
      - cardano
      - all
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./cardano-configurations/network/${NETWORK}:/config
      - ../data/${NETWORK}/mithril-aggregator/cardano/db:/db
      - ../data/${NETWORK}/mithril-aggregator/cardano/ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    command:
      [
        "run",
        "--config",
        "/config/cardano-node/config.json",
        "--topology",
        "/config/cardano-node/topology.json",
        "--database-path",
        "/db"
      ]

  mithril-aggregator:
    image: ghcr.io/input-output-hk/mithril-aggregator:${IMAGE_ID}
    container_name: mithril-aggregator
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
      - NETWORK=${NETWORK}
      - PROTOCOL_PARAMETERS__K=5
      - PROTOCOL_PARAMETERS__M=100
      - PROTOCOL_PARAMETERS__PHI_F=0.65
      - RUN_INTERVAL=60000
      - URL_SNAPSHOT_MANIFEST=https://storage.googleapis.com/cardano-${NETWORK}/snapshots.json
      - SNAPSHOT_STORE_TYPE=local
      - SNAPSHOT_UPLOADER_TYPE=local
      - DATA_STORES_DIRECTORY=/mithril-aggregator/mithril/stores
      - STORE_RETENTION_LIMIT=5
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
      - GENESIS_VERIFICATION_KEY=${GENESIS_VERIFICATION_KEY}
      - GENESIS_SECRET_KEY=${GENESIS_SECRET_KEY}
      - DB_DIRECTORY=/db
      - SNAPSHOT_DIRECTORY=/mithril-aggregator/mithril/snapshots
      - SERVER_PORT=8080
    volumes:
      - ../data/${NETWORK}/mithril-aggregator/mithril:/mithril-aggregator/mithril
      - ../data/${NETWORK}/mithril-aggregator/cardano/db:/db
      - ../data/${NETWORK}/mithril-aggregator/cardano/ipc:/ipc
    ports:
      - "8080:8080"
    command: [ "-vvv", "serve" ]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-app.rule=Host(`${AGGREGATOR_HOST}`)'
      - 'traefik.http.routers.my-app.tls=true'
      - 'traefik.http.routers.my-app.tls.certresolver=lets-encrypt'

networks:
  default:
    external:
      name: mithril_network
