[package]
name = "mithril-common"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
async-trait = "0.1.52"
blake2 = "0.9.2"
fixed = "1.15.0"
glob = "0.3"
hex = "0.4.3"
http = { version = "0.2.6", optional = true }
jsonschema = { version = "0.16.0", optional = true }
mithril = { path = "../mithril-core" }
mockall = "0.11.0"
nom = "7.1"
rand_chacha = { version = "0.3.1", optional = true }
rand_core   = "0.6.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = { version = "0.9.10", optional = true }
sha2 = "0.10.2"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_debug"] }
slog-scope = { version = "4.4.0", optional = true }
sqlite = "0.27.0"
thiserror = "1.0.31"
tokio = { version = "1.17.0", features = ["full"] }
walkdir = "2"
warp = { version = "0.3", optional = true }

[features]
portable = ["mithril/portable"]
test-utils= ["http", "jsonschema", "rand_chacha", "serde_yaml", "slog-scope", "warp"]
